force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/deptno__c.field-meta.xml
<CustomField>
    <fullName>deptno__c</fullName>
    <label>deptno</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/ename__c.field-meta.xml
<CustomField>
    <fullName>ename__c</fullName>
    <label>ename</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomSaveButton.cls
public class CustomSaveButton {

 

    public string edept { get; set; }

 

    public Integer esalary { get; set; }

 

    public String ejob { get; set; }

 

    public String ename { get; set; }

 

    public PageReference saveRecord() {
        Employee__c obj=new Employee__c();

        obj.ename__c=ename;
        obj.salary__c=esalary;
        obj.job__c=ejob;
        obj.deptno__c=edept;
        Insert obj;

        return null;
    }

 

}