force-app/main/default/objects/Hero_Employee__c/Hero_Employee__c.object-meta.xml
<CustomObject>
    <label>Hero Employee</label>
    <nameField>
        <label>Hero Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hero Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero_Employee__c/fields/Emp_Address__c.field-meta.xml
<CustomField>
    <fullName>Emp_Address__c</fullName>
    <label>Emp Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hero_Employee__c/fields/Emp_Deptt__c.field-meta.xml
<CustomField>
    <fullName>Emp_Deptt__c</fullName>
    <label>Emp Deptt</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hero_Employee__c/fields/Emp_Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Emp_Father_Name__c</fullName>
    <label>Emp Father Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmpInfo.cls
public class EmpInfo {
    
    @auraEnabled
    public static void insertEmpDetails(String enm, String efnam, String eaddr, String edept, String esal)
    {
        Hero_Employee__c hemp = new Hero_Employee__c();
        hemp.Name = enm;
        hemp.Emp_Father_Name__c = efnam;
        hemp.Emp_Address__c = eaddr;
        hemp.Emp_Deptt__c = edept;
        hemp.Emp_Salary__c = Integer.valueof(esal);
        insert hemp;
        
    }
}